# -*- coding: utf-8 -*-
"""
Created on Thu Jun  1 20:07:22 2017

@author: daphnehb
"""

#!/usr/bin/python
# -*- coding: utf-8 -*-

#import shlex
# import subprocess
import os
import time

print "*** /!\ For simulations on Sango, check that interactive=False in LGNeurons.py ***"
print "*** and that the code to be executed has been made executable: chmod +x toto.py ***"

header = '#!/bin/bash \n\n'

execTime = time.localtime()
timeString = str(execTime[0])+'_'+str(execTime[1])+'_'+str(execTime[2])+'_'+str(execTime[3])+':'+str(execTime[4])

print 'Time:', timeString

global i
i = 0 # total number of jobs launched
nbQueuedJobs = 0 # number of jobs currently in the queue

# processes for one parameterization test:
#----------------------------------------- 
def launchOneParameterizedRun(ratio=1.):
  # checks that there are not too many jobs launched, otherwise waits
  readyToGo = False
  while not readyToGo:
    os.system('squeue -u daphne-heraiz > squeueStatus.txt')

    qf = open('squeueStatus.txt','r')
    nbQueuedJobs = len(qf.readlines())-1
    qf.close()
    
    if nbQueuedJobs < 1000:
      readyToGo = True
      print nbQueuedJobs,"jobs -- Ready to launch job",i
    else:
      print nbQueuedJobs,"jobs -- Wait"
      time.sleep(60)

  # ready to launch a new job:
  IDstring = timeString+'_%05d' %(i)

  print 'Create subdirectory:',IDstring
  os.system('mkdir '+IDstring)
  os.system('cp LGneurons.py '+IDstring+'/')
  os.system('cp testFullBG.py '+IDstring+'/')
  os.system('cp plot_tools.py '+IDstring+'/')
  os.system('cp useful_auto.py '+IDstring+'/')
  os.system('cp io_gest.py '+IDstring+'/')
  os.system('cp data_tools.py '+IDstring+'/')
  os.system('cp gdf_concat.sh '+IDstring+'/')
  os.system('cp testChannelBG.py '+IDstring+'/')
  os.system('cp solutions_simple_unique.csv '+IDstring+'/')
  os.system('cp __init__.py '+IDstring+'/')
  os.chdir(IDstring)
  os.system('mkdir -p log plots data/files')

  # creation of the modelParams.py file that will correspond to the run at hand
  mltstr = '''#!/apps/free/python/2.7.10/bin/python

# defines the value of the parameters that will be used by testFullbG.py
# generated by sangoScript.py

interactive = False

params = {'nbcpu':    %s,
          'nbCh' :    %d,
          'LG14modelID': %2d,
          'whichTest': %s, # which test was used to generate the log
          'nbMSN':    %f,
          'nbFSI':    %f,
          'nbSTN':    %f,
          'nbGPe':    %f,
          'nbGPi':    %f,
          'nbCSN':    %f,
          'nbPTN':    %f,
          'nbCMPf':   %f,
          'GMSN':     %4.2f,
          'GFSI':     %4.2f,
          'GSTN':     %4.2f,
          'GGPe':     %4.2f,
          'GGPi':     %4.2f, 
          'IeGPe':    %3.1f,
          'IeGPi':    %3.1f,
          'inDegCSNMSN':  %3.f,
          'inDegPTNMSN':  %3.f,
          'inDegCMPfMSN': %3.f,
          'inDegFSIMSN':  %3.f, # according to Humphries et al. 2010, 30-150 FSIs->MSN
          'inDegMSNMSN':  %3.f, # according to Koos et al. 2004, cited by Humphries et al., 2010, on avg 3 synpase per MSN-MSN connection
          'inDegSTNMSN':  %3.f,
          'inDegGPeMSN':  %3.f,
          'inDegCSNFSI':  %3.f,
          'inDegPTNFSI':  %3.f,
          'inDegSTNFSI':  %3.f,
          'inDegGPeFSI':  %3.f,
          'inDegCMPfFSI': %3.f,
          'inDegFSIFSI':  %3.f, # according to Humphries et al., 2010, 13-63 FSIs->FSI
          'inDegPTNSTN':  %3.f,
          'inDegCMPfSTN': %3.f,
          'inDegGPeSTN':  %3.f,
          'inDegCMPfGPe': %3.f,
          'inDegSTNGPe':  %3.f,
          'inDegMSNGPe': %5.f,
          'inDegGPeGPe':  %3.f,
          'inDegMSNGPi': %5.f,
          'inDegSTNGPi':  %3.f,
          'inDegGPeGPi':  %3.f,
          'inDegCMPfGPi': %3.f,
          'ratio':        %3.f,
          }
''' %(testedParameters['nbcpu'],testedParameters['nbch'],testedParameters['lg14modelid'],testedParameters['whichTest'],testedParameters['nbmsn'],testedParameters['nbfsi'],testedParameters['nbstn'],testedParameters['nbgpe'],testedParameters['nbgpi'],testedParameters['nbcsn'],testedParameters['nbptn'],testedParameters['nbcmpf'],testedParameters['gmsn'],testedParameters['gfsi'],testedParameters['gstn'],testedParameters['ggpe'],testedParameters['ggpi'],testedParameters['iegpe'],testedParameters['iegpi'],testedParameters['inDegCSNMSN'],testedParameters['inDegPTNMSN'],testedParameters['inDegCMPfMSN'],testedParameters['inDegFSIMSN'],testedParameters['inDegMSNMSN'],testedParameters['inDegSTNMSN'],testedParameters['inDegGPeMSN'],testedParameters['inDegCSNFSI'],testedParameters['inDegPTNFSI'],testedParameters['inDegSTNFSI'],testedParameters['inDegGPeFSI'],testedParameters['inDegCMPfFSI'],testedParameters['inDegFSIFSI'],testedParameters['inDegPTNSTN'],testedParameters['inDegCMPfSTN'],testedParameters['inDegGPeSTN'],testedParameters['inDegCMPfGPe'],testedParameters['inDegSTNGPe'],testedParameters['inDegMSNGPe'],testedParameters['inDegGPeGPe'],testedParameters['inDegMSNGPi'],testedParameters['inDegSTNGPi'],testedParameters['inDegGPeGPi'],testedParameters['inDegCMPfGPi'],ratio)

  print 'Write modelParams.py'
  paramsFile = open('modelParams.py','w')
  paramsFile.writelines(mltstr)
  paramsFile.close()

  # #SBATCH --mem-per-cpu=1G changed for #SBATCH --mem-per-cpu=200M
  slurmOptions = ['#SBATCH --time='+testedParameters['durationH']+':'+testedParameters['durationMin']+':00 \n',
                  '#SBATCH --partition=compute \n',
                  '#SBATCH --mem-per-cpu=1G \n',
                  '#SBATCH --ntasks=1 \n',
                  '#SBATCH --cpus-per-task='+testedParameters['nbcpu']+' \n',
                  '#SBATCH --job-name=sBCBG_'+IDstring+'\n',
                  '#SBATCH --input=none\n',
                  '#SBATCH --output="'+IDstring+'.out" \n',
                  '#SBATCH --error="'+IDstring+'.err" \n',
                  '#SBATCH --mail-user=daphne-heraiz@oist.jp \n',
                  '#SBATCH --mail-type=FAIL \n',
                  ]

  moduleUse = ['module use /apps/unit/DoyaU/.modulefiles/ \n']

  moduleLoad = ['module load nest/2.10 \n']

  # write the script file
  print 'Write slurm script file'
  script = open('go.slurm','w')
  script.writelines(header)
  script.writelines(slurmOptions)
  script.writelines(moduleUse)
  script.writelines(moduleLoad)
  #script.writelines('python testFullBG.py \n')
  #script.writelines('python testChannelBG.py \n')
  script.writelines('time srun --mpi=pmi2 python '+testedParameters['whichTest']+'.py \n')
  script.close()

  # execute the script file
  command = 'sbatch go.slurm'
  os.system(command)

  os.chdir('..')

#===============================

# with which additional parameters?
testedParameters = {'durationH':  '01',
                  'durationMin':  '30',
                  'nbcpu':        '8',
                  'whichTest':    'useful_auto',
                  'nbch':   2,
                  'lg14modelid':  9,
                  'nbmsn':2644.,
                  'nbfsi':  53.,
                  'nbstn':   8.,
                  'nbgpe':  25.,
                  'nbgpi':  14.,
                  'nbcsn':3000.,
                  'nbptn': 100.,
                  'nbcmpf':  9.,
                  'gmsn':    4.,
                  'gfsi':    1.,
                  'gstn':    1.4,
                  'ggpe':    1.,
                  'ggpi':    1.,
                  'iegpe':  11.,
                  'iegpi':  11.,
                  }

# getting the model settings
import useful_auto as auto
auto.switch_model(testedParameters['lg14modelid'])
testedParameters.update(params)


ftp = open(timeString+'_testedParameter.txt','w')
for k,vlist in testedParameters.iteritems():
  ftp.writelines(str(k)+' '+str(vlist)+'\n')
ftp.close()

#------------------------------
# recursive exploration of all parameter combinations defined in pdict dictionary
#------------------------------
def recParamExplo(intervalle):
  for i in np.arange(*intervalle) :
    launchOneParameterizedRun(ratio=i)



recParamExplo((1.,2.,0.1))
